### PR TITLE
Run jupyter job on slurm and connect with port forwarding

### PR DESCRIPTION
**Pull request by skarakulak**

### CODE REVIEW

**Comment by Atcold** [comment]
Hmm, why not running it in an interactive session? We have two of them!

**Comment by skarakulak** [comment]
I use interactive session as well. But when you lose your connection, you lose the interactive session too. So submitting a job is sometimes more convenient if I plan to work on the notebook for a while.

**Comment by Atcold** [comment]
**Not** if you use `tmux` 😜

**Comment by Atcold** [comment]
Pushing now the latest settings. Pull them and you should be good to go.

**Comment by Atcold** [comment]
Namely, see: 163016ed3a3d13ba6d76a819b1e6708064f6f2ab and 8c1747cfe482dc4824d982ce340a164a94fa44d6.

**Pull request closed without merging**
